name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    name: Run Selenium Test
    runs-on: ubuntu-latest  # Wybór systemu operacyjnego do uruchomienia testu

    # Użycie usługi Docker z Selenium (chociaż w tym przypadku, możesz używać systemu, który ma zainstalowaną przeglądarkę)
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444  # Port na którym działa Selenium Server (Domyślnie 4444)
        options: >-
          --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep -q '\"ready\":true'"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=3

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK (jeśli używasz JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 3. Install dependencies using Maven
      - name: Install dependencies
        run: |
          mvn install

      # 4. Run Selenium test (uruchamiamy testy w trybie headless)
      - name: Run Selenium tests
        run: |
          mvn test